#!/bin/bash

echo "🚀 ParallelAI Usage Examples"
echo "============================"
echo ""
echo "1. Basic query to all providers:"
echo "   ./parallelai query \"What is machine learning?\""
echo ""
echo "2. Query specific provider:"
echo "   ./parallelai query --provider anthropic \"Explain neural networks\""
echo "   ./parallelai query --provider groq \"What is deep learning?\""
echo "   ./parallelai query --provider together \"Explain transformers\""
echo "   ./parallelai query --provider openrouter \"What is reinforcement learning?\""
echo ""
echo "3. Compare provider responses:"
echo "   ./parallelai query \"Compare supervised and unsupervised learning\""
echo ""
echo "4. Key management:"
echo "   ./parallelai keys list          # List all API keys"
echo "   ./parallelai keys test          # Test all API keys"
echo "   ./parallelai keys setup         # Interactive setup"
echo ""
echo "5. Research examples:"
echo "   ./parallelai query \"Analyze the ethical implications of AI\""
echo "   ./parallelai query \"Compare GPT-4 and Claude 3 capabilities\""
echo "   ./parallelai query \"What are the latest advances in AI safety?\""
echo ""
echo "🎯 Try it now:"
echo "   ./parallelai query \"What makes ParallelAI unique?\""
